-- MySQL Script generated by MySQL Workbench
-- Sat Dec 31 03:26:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HRMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regions` (
  `id` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `countries` (
  `id` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NULL,
  `regions_id` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_countries_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations` (
  `id` VARCHAR(225) NOT NULL,
  `street_address` VARCHAR(225) NULL,
  `city` VARCHAR(225) NULL,
  `countries_id` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_locations_countries1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departments` (
  `id` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NULL,
  `locations_id` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`, `locations_id`),
  CONSTRAINT `fk_departments_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobs` (
  `id` VARCHAR(225) NOT NULL,
  `title` VARCHAR(225) NULL,
  `min_salary` VARCHAR(225) NULL,
  `max_salary` VARCHAR(225) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees` (
  `id` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NULL,
  `email` VARCHAR(225) NULL,
  `phone_number` VARCHAR(225) NULL,
  `hire_date` DATE NULL,
  `salary` VARCHAR(225) NULL,
  `jobs_id` VARCHAR(225) NOT NULL,
  `departments_id` VARCHAR(225) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employees_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `jobs_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobs_histories` (
  `jobs_id` VARCHAR(225) NOT NULL,
  `departments_id` VARCHAR(225) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `employees_id` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`jobs_id`, `departments_id`),
  CONSTRAINT `fk_jobs_has_departments_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_has_departments_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_histories_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
